
// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

import { type RouteType as Route_0 } from "./src/pages/auth/sign-in";
import { type RouteType as Route_1 } from "./src/pages/auth/sign-up";
import type { InferRoute, StaticRoute } from "next-typesafe-url";

declare module "@@@next-typesafe-url" {
  interface DynamicRouter {
    "/auth/sign-in": InferRoute<Route_0>;
    "/auth/sign-up": InferRoute<Route_1>;
  }

  interface StaticRouter {
    "/createagoon": StaticRoute;
    "/dressup/[petId]": StaticRoute;
    "/": StaticRoute;
    "/minigames/button": StaticRoute;
    "/minigames": StaticRoute;
    "/nijiexpress": StaticRoute;
    "/petcreator": StaticRoute;
    "/pets": StaticRoute;
    "/pets/[petId]": StaticRoute;
    "/playground": StaticRoute;
  }
}
