
// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

import type { InferRoute, StaticRoute } from "next-typesafe-url";

declare module "@@@next-typesafe-url" {
  interface DynamicRouter {
  
  }

  interface StaticRouter {
    "/auth/sign-up": StaticRoute;
    "/createagoon": StaticRoute;
    "/dressup/[petId]": StaticRoute;
    "/": StaticRoute;
    "/nijiexpress": StaticRoute;
    "/petcreator": StaticRoute;
    "/pets": StaticRoute;
    "/pets/[petId]": StaticRoute;
    "/playground": StaticRoute;
  }
}
