import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const userQuery = api.example.hello.useQuery({ text: "swaggings" });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-grow bg-white p-4">
        <p>Play some games!</p>
        <p>{userQuery.data?.greeting}</p>
      </main>
    </>
  );
};

export default Home;
