import { type NextPage } from "next";
import Head from "next/head";

const CreatePet: NextPage = () => {
  return (
    <>
      <Head>
        <title>Nijipets | Nijisanji Express</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-grow">
        <iframe className="flex-grow" src="https://vrclist.com/world/335222" />
      </main>
    </>
  );
};

export default CreatePet;
